kuromoji.dict.file=mecab-ipadic-2.7.0-20070801.tar.gz
kuromoji.dict.url=https://www.atilika.com/releases/mecab-ipadic/${kuromoji.dict.file}
kuromoji.dict.dir=cache/mecab-ipadic-2.7.0-20070801
kuromoji.dict.targetdir=../../resources/com/atilika/kuromoji/ipadic
kuromoji.dict.encoding=euc-jp
kuromoji.dict.content-length=12208105
kuromoji.dict.last-modified=Thu, 15 Nov 2018 03:03:33 GMT
kuromoji.dict.etag="347fac8bb226c4f6d34f9a652868dbd9-2"
kuromoji.dict.sha256=b62f527d881c504576baed9c6ef6561554658b175ce6ae0096a60307e49e3523
kuromoji.dict.source-pom=https://github.com/atilika/kuromoji/blob/master/kuromoji-ipadic/pom.xml
